module.exports = {
  fly_verbs: [
    "flying",
    "soaring",
    "fluttering",
    "rising",
    "ascending",
    "falling",
    "floating",
    "flapping",
    "whispering",
    "gliding",
    "sweeping",
  ],
  prepositions: ["through", "past", "within", "among", "above"],
  adverbs: [
    "noiselessly",
    "silently",
    "imperceptibly",
    "smoothly",
    "stochastically",
  ],
  spaces: ["ether", "flame", "light", "plasma", "blackness", "absence", "void"],
  emotion_verbs: [
    "fear",
    "feel like reaching for",
    "hope for a higher existence through",
  ],
  body_nouns: ["wing", "proboscis", "antenna", "forewing", "compound eye"],
  body_verbs: ["vibrates", "glides", "reaches", "hums"],
  adjectives: [
    "unanswering",
    "opaque",
    "vibrationless",
    "clean",
    "formless",
    "insentient",
  ],
  phrase: [
    "#fly_verbs.capitalize#, #fly_verbs# \n  #adverbs# #prepositions# the #spaces#",
  ],
  phrase2: ["#adverbs# \n #adverbs#"],
  phrase3: ["I #emotion_verbs# the #spaces#"],
  phrase4: [
    "My #body_nouns# #body_verbs# #prepositions# the #adjectives# #spaces#",
  ],
};
